package uk.gov.hmcts.reform.civil.model.documents;

public enum DocumentType {

    GENERAL_ORDER,
    DIRECTION_ORDER,
    DISMISSAL_ORDER,
    REQUEST_FOR_INFORMATION,
    HEARING_ORDER,
    HEARING_FORM,
    WRITTEN_REPRESENTATION_SEQUENTIAL,
    WRITTEN_REPRESENTATION_CONCURRENT,
    HEARING_NOTICE,
    CONSENT_ORDER,
    GENERAL_APPLICATION_DRAFT,
    FREE_FORM_ORDER,
    SEND_APP_TO_OTHER_PARTY,
    POST_JUDGE_ORDER_REQUEST_FOR_INFORMATION_LIP,
    POST_JUDGE_ORDER_SEND_APP_TO_OTHER_PARTY;
}
