package uk.gov.hmcts.reform.civil.model.documents;

public enum DocumentType {

    GENERAL_ORDER,
    DIRECTION_ORDER,
    DISMISSAL_ORDER,
    REQUEST_FOR_INFORMATION,
    HEARING_ORDER,
    HEARING_FORM,
    WRITTEN_REPRESENTATION_SEQUENTIAL,
    WRITTEN_REPRESENTATION_CONCURRENT,
    HEARING_NOTICE,
    CONSENT_ORDER,
    WITNESS,
    BUNDLE,
    COSTS_SCHEDULE,
    GENERAL_APPLICATION_DRAFT,
    FREE_FORM_ORDER;
}
