server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  health:
    case-document-am-api:
      enabled: true
spring:
  application:
    name: civil-general-applications
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: userInfoCache, accessTokenCache
    caffeine:
      spec: expireAfterAccess=3600s
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${idam.web.url}/o
        registration:
          oidc:
            client-id: internal
            client-secret: internal
  flyway:
    enabled: ${REFERENCE_DATABASE_MIGRATION:false}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.civil.controllers

oidc:
  issuer: ${OIDC_ISSUER:http://fr-am:8080/openam/oauth2/hmcts}

fees:
  api:
    service: civil money claims
    jurisdiction1: civil
    jurisdiction2: county court
    channel: default
    event: issue

genApp:
  authorised-services: ${GA_S2S_AUTHORISED_SERVICES:payment_app,ccd_data,civil_service}
  fee:
    endpoint: /fees-register/fees/lookup
    service: general
    jurisdiction1: civil
    jurisdiction2: civil
    channel: default
    event: general application
    keywords:
      withNotice: GAOnNotice
      consentedOrWithoutNotice: GeneralAppWithoutNotice
      uncloakFee: HACFOOnNotice
      appnToVaryOrSuspend: AppnToVaryOrSuspend
  lrd:
    endpoint: /refdata/location/court-venues


payments:
  api:
    site_id: AAA7
    service: CIVIL
    spec_site_id: AAA6
    callback-url: ${PAY_CALLBACK_URL:}

idam:
  s2s-auth:
    microservice: civil_general_applications
  s2s-authorised:
    services: ${GA_S2S_AUTHORISED_SERVICES:payment_app,ccd_data,civil_service}

document_management:
  userRoles: "caseworker-civil,caseworker-civil-solicitor"
  secured: true

bankHolidays:
  api:
    url: https://www.gov.uk

nonworking-days:
  datafile: /data/non-working_days.dat

civil:
  response-pack-url: https://formfinder.hmctsformfinder.justice.gov.uk/n9-eng.pdf
  system-update:
    username: ${CIVIL_SYSTEM_UPDATE_USERNAME:civil-system-update@mailnesia.com}
    password: ${CIVIL_SYSTEM_UPDATE_PASSWORD:Password12!}
  prd-admin:
    username: ${CIVIL_PRD_ADMIN_USERNAME:civil.prd.admin@example.com}
    password: ${CIVIL_PRD_ADMIN_PASSWORD:Password12!}
  cross-access:
    username: ${CIVIL_CROSS_ACCESS_USERNAME:caseworker-caa@mailnesia.com}
    password: ${CIVIL_CROSS_ACCESS_PASSWORD:Password12!}

core_case_data:
  api:
    url: http://localhost:4452
case_document_am:
  url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}
reference:
  database:
    enabled: true
    migration: false

notifications:
  govNotifyApiKey: ${GOV_NOTIFY_API_KEY:}
  generalApplicationRespondentEmailTemplate: "487ecc1a-5ec6-4d04-ba13-d92e27ef805f"
  withNoticeUpdateRespondentEmailTemplate: "65da2ccc-61c6-4a8a-8f82-7a3b3029e73f"
  writtenRepConcurrentRepresentationApplicantEmailTemplate : "f55694b9-04e6-4a17-bec0-09255e5f096e"
  writtenRepConcurrentRepresentationRespondentEmailTemplate : "df663c94-5e87-457a-9e85-723245da70f1"
  writtenRepSequentialRepresentationApplicantEmailTemplate : "56d4ad11-ee6d-4ef7-9b83-cce78377f01b"
  writtenRepSequentialRepresentationRespondentEmailTemplate : "ffd74057-0204-4185-95de-5bb715e80e6c"
  judgeListsForHearingApplicantEmailTemplate: "7a1d9e5b-4b1d-4765-b5de-d191d6c91a11"
  judgeListsForHearingRespondentEmailTemplate: "3075b0c1-b19a-4f61-82d6-78c27bfedb8a"
  judgeForApprovedCaseApplicantEmailTemplate: "dc15208c-e68a-4656-a88a-0f1d40e25845"
  judgeForApproveRespondentEmailTemplate: "5ccc25e7-be62-4815-a87b-2c5387451962"
  judgeDismissesOrderApplicantEmailTemplate: "96f708e8-0a03-40ef-9278-a5dcfa3277fa"
  judgeDismissesOrderRespondentEmailTemplate: "ed46fc96-620b-4791-a1e7-f6a93c89447c"
  judgeForDirectionOrderApplicantEmailTemplate: "d4f1d7f0-d9cf-4295-bc87-502bab67170f"
  judgeForDirectionOrderRespondentEmailTemplate: "20c146c4-71e4-4469-8efa-b0ed8bf87c67"
  judgeRequestForInformationApplicantEmailTemplate: "e16c98d5-8e4a-4d15-9103-1b5970693e80"
  judgeRequestForInformationRespondentEmailTemplate: "d16dd83e-1403-486d-a6d9-0f44ddcbaf01"
  judgeUncloakApplicationEmailTemplate: "251414bb-3f26-47c6-ba1d-d7254349c028"
  judgeApproveOrderToStrikeOutDamages: "073b4650-c4c5-478a-8824-3c495a8e29e5"
  judgeApproveOrderToStrikeOutOCMC: "5c6de4de-4a8b-4775-8b20-1fea6d0c1a6a"
  hearingNoticeTemplate: "03763ce1-de17-4a9a-b1c6-d2e9ccffe9d7"

os-postcode-lookup:
  url: https://api.os.uk/search/names/v1/find
  key: ${OS_POSTCODE_LOOKUP_API_KEY:}
  offline-mode: false

stitching:
  api:
    url: http://localhost:8084/api/stitch-ccd-bundles

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:}
  offline-mode: false
  env: ${LAUNCH_DARKLY_ENV:default}

testing:
  support:
    enabled: ${TESTING_SUPPORT_ENABLED:false}

exit-survey:
  applicant-link: https://www.smartsurvey.co.uk/s/CivilDamages_ExitSurvey_Claimant/
  respondent-link: https://www.smartsurvey.co.uk/s/CivilDamages_ExitSurvey_Defendant/

---

spring:
  config:
    activate:
      on-profile: local

feign:
  client:
    config:
      remoteRuntimeService:
        url: http://localhost:9404/engine-rest/
      remoteRepositoryService:
        url: http://localhost:9404/engine-rest/
      remoteExternalTaskService:
        url: http://localhost:9404/engine-rest/
      idam-api:
        loggerLevel: full
      core-case-data-api:
        loggerLevel: full
      document-management-metadata-download-api:
        loggerLevel: full
fees:
  api:
    url: http://localhost:8765

genApp:
  lrd:
    url: http://localhost:8765

payments:
  api:
    url: http://localhost:8765
    callback-url: http://localhost:4550/service-request-update

idam:
  web:
    url: http://localhost:9002
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH
  client:
    id: civil
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO

document_management:
  url: http://localhost:3453

docmosis:
  tornado:
    url: http://localhost:5433

sendgrid:
  api-key: ${SENDGRID_API_KEY:false}

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:fake-key}

testing:
  support:
    enabled: true

rd_professional:
  api:
    url: http://localhost:8765

robotics:
  notification:
    sender: hmcts.civil@gmail.com
    recipient: hmcts.civil+robotics@gmail.com
---

spring:
  config:
    activate:
      on-profile: integration-test

  main:
    lazy-initialization: true

management:
  endpoints:
    enabled-by-default: false

fees:
  api:
    url: http://fake-fees-register-api

genApp:
  lrd:
    url: http://fake-rd-location-ref-api

payments:
  api:
    url: http://fake-payment-register-api
    callback-url: http://fake-payment-register-api

idam:
  web:
    url: http://fake-idam-web
  api:
    url: http://fake-idam-api
  s2s-auth:
    url: http://fake-service-auth-provider-api
    totp_secret: AABBCCDDEEFFGGHH

core_case_data:
  api:
    url: http://fake-ccd-data-store-api

reference:
  database:
    enabled: false

document_management:
  url: http://fake-document-management-api

docmosis:
  tornado:
    url: http://fake-docmosis-api
    key: fake-key

feign:
  client:
    config:
      remoteRuntimeService:
        url: http://fake/engine-rest/
      remoteRepositoryService:
        url: http://fake/engine-rest/
      remoteExternalTaskService:
        url: http://fake/engine-rest/

notifications:
  govNotifyApiKey: some-gov-uk-notify-api-key

testing:
  support:
    enabled: true

rd_professional:
  api:
    url: http://fake-prd-api

sendgrid:
  api-key: fake-key
---

spring:
  config:
    activate:
      on-profile: idam-stub

idam:
  web:
    url: http://ccd-test-stubs-service:5555
  api:
    url: http://ccd-test-stubs-service:5555
