server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  health:
    db:
      enabled: false
    case-document-am-api:
      enabled: true
spring:
  config:
    import: "optional:configtree:/mnt/secrets/civil/, optional:configtree:/mnt/secrets/civil-gen-apps/"
  application:
    name: civil-general-applications
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: userInfoCache, accessTokenCache
    caffeine:
      spec: expireAfterAccess=3600s
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${CMC_DB_USERNAME:-}
    password: ${CMC_DB_PASSWORD:-}
    url: jdbc:postgresql://${CMC_DB_HOST:}:${CMC_DB_PORT:}/${CMC_DB_NAME:cmc}${CMC_DB_CONNECTION_OPTIONS:}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${idam.web.url}/o
        registration:
          oidc:
            client-id: internal
            client-secret: internal

location:
  api:
    baseUrl: ${GENAPP_LRD_URL:http://localhost:8765}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.civil.controllers

oidc:
  issuer: ${OIDC_ISSUER:http://fr-am:8080/openam/oauth2/hmcts}

send-letter:
  url: ${SEND_LETTER_URL:http://localhost:8765}

fees:
  api:
    service: civil money claims
    jurisdiction1: civil
    jurisdiction2: county court
    channel: default
    event: issue

genApp:
  authorised-services: ${GA_S2S_AUTHORISED_SERVICES:payment_app,ccd_data,civil_service}
  fee:
    endpoint: /fees-register/fees/lookup
    service: general
    jurisdiction1: civil
    jurisdiction2: civil
    channel: default
    event: general application
    keywords:
      withNotice: GAOnNotice
      consentedOrWithoutNotice: GeneralAppWithoutNotice
      uncloakFee: HACFOOnNotice
      appnToVaryOrSuspend: AppnToVaryOrSuspend
      certificateOfSatisfaction: CoS
  lrd:
    endpoint: /refdata/location/court-venues


payments:
  api:
    site_id: AAA7
    service: CIVIL
    spec_site_id: AAA6
    callback-url: ${PAY_CALLBACK_URL:}

idam:
  s2s-auth:
    microservice: civil_general_applications
  s2s-authorised:
    services: ${GA_S2S_AUTHORISED_SERVICES:payment_app,ccd_data,civil_service}

document_management:
  userRoles: "caseworker-civil,caseworker-civil-solicitor"

bankHolidays:
  api:
    url: https://www.gov.uk

nonworking-days:
  datafile: /data/non-working_days.dat

civil:
  response-pack-url: https://formfinder.hmctsformfinder.justice.gov.uk/n9-eng.pdf
  system-update:
    username: ${CIVIL_SYSTEM_UPDATE_USERNAME:civil-system-update@mailnesia.com}
    password: ${CIVIL_SYSTEM_UPDATE_PASSWORD:Password12!}
  prd-admin:
    username: ${CIVIL_PRD_ADMIN_USERNAME:civil.prd.admin@example.com}
    password: ${CIVIL_PRD_ADMIN_PASSWORD:Password12!}
  cross-access:
    username: ${CIVIL_CROSS_ACCESS_USERNAME:caseworker-caa@mailnesia.com}
    password: ${CIVIL_CROSS_ACCESS_PASSWORD:Password12!}

core_case_data:
  api:
    url: http://localhost:4452
case_document_am:
  url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}
reference:
  database:
    enabled: true
    migration: false

dashboard:
  api:
    url: ${DASHBOARD_API_URL:http://localhost:4000}

notifications:
  govNotifyApiKey: ${GOV_NOTIFY_API_KEY:}
  generalApplicationRespondentEmailTemplate: "487ecc1a-5ec6-4d04-ba13-d92e27ef805f"
  urgentGeneralAppRespondentEmailTemplate: "3ae23a46-a83b-4768-a066-198e80958cea"
  lipGeneralAppRespondentEmailTemplate: "39d8c00f-2597-4e39-80a9-0f53c05715be"
  lipGeneralAppRespondentEmailTemplateInWelsh: "acc28d80-8e15-4b8f-a439-e990bbddeea4"
  lipGeneralAppApplicantEmailTemplate: "64c4047f-3256-45ff-9b4e-9a11bccf14fe"
  lipGeneralAppApplicantEmailTemplateInWelsh: "954f1d99-eb42-4151-b799-157c969f043f"
  withNoticeUpdateRespondentEmailTemplate: "65da2ccc-61c6-4a8a-8f82-7a3b3029e73f"
  writtenRepConcurrentRepresentationApplicantEmailTemplate : "f55694b9-04e6-4a17-bec0-09255e5f096e"
  writtenRepConcurrentRepresentationRespondentEmailTemplate : "df663c94-5e87-457a-9e85-723245da70f1"
  writtenRepSequentialRepresentationApplicantEmailTemplate : "56d4ad11-ee6d-4ef7-9b83-cce78377f01b"
  writtenRepSequentialRepresentationRespondentEmailTemplate : "ffd74057-0204-4185-95de-5bb715e80e6c"
  judgeListsForHearingApplicantEmailTemplate: "7a1d9e5b-4b1d-4765-b5de-d191d6c91a11"
  judgeListsForHearingRespondentEmailTemplate: "3075b0c1-b19a-4f61-82d6-78c27bfedb8a"
  judgeForApprovedCaseApplicantEmailTemplate: "dc15208c-e68a-4656-a88a-0f1d40e25845"
  judgeForApproveRespondentEmailTemplate: "5ccc25e7-be62-4815-a87b-2c5387451962"
  judgeDismissesOrderApplicantEmailTemplate: "96f708e8-0a03-40ef-9278-a5dcfa3277fa"
  judgeDismissesOrderRespondentEmailTemplate: "ed46fc96-620b-4791-a1e7-f6a93c89447c"
  judgeForDirectionOrderApplicantEmailTemplate: "d4f1d7f0-d9cf-4295-bc87-502bab67170f"
  judgeForDirectionOrderRespondentEmailTemplate: "20c146c4-71e4-4469-8efa-b0ed8bf87c67"
  judgeRequestForInformationApplicantEmailTemplate: "e16c98d5-8e4a-4d15-9103-1b5970693e80"
  judgeRequestForInformationRespondentEmailTemplate: "d16dd83e-1403-486d-a6d9-0f44ddcbaf01"
  judgeUncloakApplicationEmailTemplate: "251414bb-3f26-47c6-ba1d-d7254349c028"
  judgeApproveOrderToStrikeOutDamages: "073b4650-c4c5-478a-8824-3c495a8e29e5"
  judgeApproveOrderToStrikeOutOCMC: "5c6de4de-4a8b-4775-8b20-1fea6d0c1a6a"
  hearingNoticeTemplate: "3122b710-2c42-4635-8bbc-e0ac72fc27f5"
  evidenceUploadTemplate: "7bf848bc-ff64-471e-b780-2961a010b6f0"
  notifyApplicantForHwFMoreInformationNeeded: "02956398-fffb-4461-93a0-3713788363a8"
  notifyApplicantForHwfInvalidRefNumber: "8d7cb08f-96ae-4469-944d-c92650f45fb6"
  notifyApplicantForHwfUpdateRefNumber: "7f87e629-6473-4732-8d80-4174d06696d5"
  notifyApplicantForHwfPartialRemission: "2c5c5cae-f1b1-41b5-afe5-0ce2e68f8d3c"
  notifyApplicantForNoRemission: "3008a18a-07ec-445b-a226-62ffa19132ce"
  notifyApplicantForHwfPaymentOutcome: "64c4047f-3256-45ff-9b4e-9a11bccf14fe"
  notifyApplicantLiPTranslatedDocumentUploadedWhenParentCaseInBilingual: "954f1d99-eb42-4151-b799-157c969f043f"
  notifyRespondentLiPTranslatedDocumentUploadedWhenParentCaseInBilingual: "acc28d80-8e15-4b8f-a439-e990bbddeea4"
  notifyLRTranslatedDocumentUploaded: "c3bde074-9da5-469a-9aa4-7a80d9cfae1b"
  notifyApplicantForHwfInvalidRefNumberBilingual: "8950e206-6d15-4575-9d99-734908389fa7"
  notifyApplicantForHwFMoreInformationNeededWelsh: "70267e5b-9f11-4549-bc59-56bf7fbdeca7"
  notifyApplicantForHwfNoRemissionWelsh: "f9d2f0db-2ae4-4691-8076-bfbb82548846"
  notifyApplicantForHwfUpdateRefNumberBilingual: "a7c206b5-8a27-4419-83ff-61351cbc69fb"
  notifyApplicantForHwfPartialRemissionBilingual: "5bbd4518-5501-4737-8a1e-a6adacd5e679"

sendgrid:
  api-key: ${SENDGRID_API_KEY:false}

os-postcode-lookup:
  url: https://api.os.uk/search/names/v1/find
  key: ${OS_POSTCODE_LOOKUP_API_KEY:}
  offline-mode: false

print:
  service:
    enabled: true

stitching:
  api:
    url: http://localhost:8084/api/stitch-ccd-bundles

court-location:
  specified-claim:
    epimms-id: "420219"
  unspecified-claim:
    epimms-id: "192280"

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:}
  offline-mode: false
  env: ${LAUNCH_DARKLY_ENV:default}

testing:
  support:
    enabled: ${TESTING_SUPPORT_ENABLED:false}

exit-survey:
  applicant-link: https://www.smartsurvey.co.uk/s/CivilDamages_ExitSurvey_Claimant/
  respondent-link: https://www.smartsurvey.co.uk/s/CivilDamages_ExitSurvey_Defendant/

cui-front-end:
  url: ${CUI_URL:http://localhost:3001}

feign:
  client:
    config:
      remoteRuntimeService:
        url: ${CAMUNDA_URL:http://localhost:9404/engine-rest/}
      processInstance:
        url: ${CAMUNDA_URL:http://localhost:9404/engine-rest/}
      processDefinition:
        url: ${CAMUNDA_URL:http://localhost:9404/engine-rest/}
      message:
        url: ${CAMUNDA_URL:http://localhost:9404/engine-rest/}
      incident:
        url: ${CAMUNDA_URL:http://localhost:9404/engine-rest/}
      externalTask:
        url: ${CAMUNDA_URL:http://localhost:9404/engine-rest/}
---

spring:
  config:
    activate:
      on-profile: local

feign:
  client:
    config:
      idam-api:
        loggerLevel: full
      core-case-data-api:
        loggerLevel: full
      document-management-metadata-download-api:
        loggerLevel: full
fees:
  api:
    url: http://localhost:8765

print:
  service:
    enabled: false

genApp:
  lrd:
    url: http://localhost:8765

payments:
  api:
    url: http://localhost:8765
    callback-url: http://localhost:4550/service-request-update

idam:
  web:
    url: http://localhost:9002
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH
  client:
    id: civil
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO

document_management:
  url: http://localhost:3453

docmosis:
  tornado:
    url: http://localhost:5433

sendgrid:
  api-key: ${SENDGRID_API_KEY:false}

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:fake-key}

testing:
  support:
    enabled: true

rd_professional:
  api:
    url: http://localhost:8765

robotics:
  notification:
    sender: hmcts.civil@gmail.com
    recipient: hmcts.civil+robotics@gmail.com
---

spring:
  config:
    activate:
      on-profile: integration-test

  main:
    lazy-initialization: true

management:
  endpoints:
    enabled-by-default: false

print:
  service:
    enabled: true

fees:
  api:
    url: http://fake-fees-register-api

genApp:
  lrd:
    url: http://fake-rd-location-ref-api

payments:
  api:
    url: http://fake-payment-register-api
    callback-url: http://fake-payment-register-api

idam:
  web:
    url: http://fake-idam-web
  api:
    url: http://fake-idam-api
  s2s-auth:
    url: http://fake-service-auth-provider-api
    totp_secret: AABBCCDDEEFFGGHH

core_case_data:
  api:
    url: http://fake-ccd-data-store-api

reference:
  database:
    enabled: false

document_management:
  url: http://fake-document-management-api

docmosis:
  tornado:
    url: http://localhost:6660
    key: fake-key

feign:
  client:
    config:
      remoteRuntimeService:
        url: http://fake/engine-rest/
      remoteRepositoryService:
        url: http://fake/engine-rest/
      remoteExternalTaskService:
        url: http://fake/engine-rest/

notifications:
  govNotifyApiKey: some-gov-uk-notify-api-key

testing:
  support:
    enabled: true

rd_professional:
  api:
    url: http://localhost:6665

sendgrid:
  api-key: ${SENDGRID_API_KEY:fake-key}
---

spring:
  config:
    activate:
      on-profile: idam-stub

idam:
  web:
    url: http://ccd-test-stubs-service:5555
  api:
    url: http://ccd-test-stubs-service:5555
  sendgrid:
    api-key: ${SENDGRID_API_KEY:false}
