package uk.gov.hmcts.reform.civil.model.citizenui;

public enum TranslatedDocumentType {
    APPLICATION_SUMMARY_DOCUMENT,
    APPLICATION_SUMMARY_DOCUMENT_RESPONDED,
    REQUEST_FOR_MORE_INFORMATION_ORDER,
    HEARING_ORDER,
    GENERAL_ORDER,
    DISMISSAL_ORDER,
    JUDGES_DIRECTIONS_ORDER,
    WRITTEN_REPRESENTATIONS_ORDER,
    HEARING_NOTICE,
    WITHOUT_NOTICE_TO_WITH_NOTICE_DOCUMENT,
    UPLOADED_DOCUMENTS_APPLICANT,
    UPLOADED_DOCUMENTS_RESPONDENT,
    WRITTEN_REPRESENTATIONS_APPLICANT,
    WRITTEN_REPRESENTATIONS_RESPONDENT,
    REQUEST_MORE_INFORMATION_APPLICANT,
    REQUEST_MORE_INFORMATION_RESPONDENT,
    JUDGES_DIRECTIONS_APPLICANT,
    JUDGES_DIRECTIONS_RESPONDENT,
    APPROVE_OR_EDIT_ORDER
}
