package uk.gov.hmcts.reform.civil.service.flowstate;

public enum FlowFlag {
    ONE_RESPONDENT_REPRESENTATIVE,
    TWO_RESPONDENT_REPRESENTATIVES,
    RPA_CONTINUOUS_FEED,
    LIP_APPLICANT,
    LIP_RESPONDENT,
    POST_JUDGE_ORDER_LIP_APPLICANT,
    POST_JUDGE_ORDER_LIP_RESPONDENT
}
