package uk.gov.hmcts.reform.civil.service.flowstate;

public enum FlowFlag {
    ONE_RESPONDENT_REPRESENTATIVE,
    TWO_RESPONDENT_REPRESENTATIVES,
    RPA_CONTINUOUS_FEED,
    LIP_APPLICANT,
    LIP_RESPONDENT,
    VARY_JUDGE_GA_BY_RESP,
    POST_JUDGE_ORDER_LIP_APPLICANT,
    POST_JUDGE_ORDER_LIP_RESPONDENT,
    WELSH_ENABLED,
    WELSH_ENABLED_FOR_JUDGE_DECISION,
    FREE_FEE_WELSH_APPLICATION
}
