package uk.gov.hmcts.reform.civil.utils;

public enum NotificationCriterion {
    CONCURRENT_WRITTEN_REP,
    SEQUENTIAL_WRITTEN_REP,
    LIST_FOR_HEARING,
    APPLICATION_MOVES_TO_WITH_NOTICE,
    JUDGE_DISMISSED_APPLICATION,
    JUDGE_APPROVED_THE_ORDER,
    APPLICANT_WRITTEN_REP_CONCURRENT,
    APPLICANT_WRITTEN_REP_SEQUENTIAL,
    JUDGE_APPROVED_THE_ORDER_CLOAK,
    JUDGE_DISMISSED_APPLICATION_CLOAK,
    JUDGE_DIRECTION_ORDER_CLOAK,
    JUDGE_DIRECTION_ORDER,
    REQUEST_FOR_INFORMATION,
    NON_CRITERION
}
