package uk.gov.hmcts.reform.civil.utils;

public enum NotificationCriterion {
    CONCURRENT_WRITTEN_REP,
    SEQUENTIAL_WRITTEN_REP,
    LIST_FOR_HEARING,
    APPLICATION_UNCLOAK,
    APPLICATION_MOVES_TO_WITH_NOTICE,
    JUDGE_DISMISSED_APPLICATION,
    JUDGE_APPROVED_THE_ORDER,
    APPLICANT_WRITTEN_REP_CONCURRENT,
    APPLICANT_WRITTEN_REP_SEQUENTIAL,
    NON_CRITERION
}
