package uk.gov.hmcts.reform.civil.utils;

public enum NotificationCriterion {

    JUDGE_DISMISSED_APPLICATION,
    JUDGE_DISMISSED_APPLICATION_CLOAK,
    JUDGE_APPROVED_THE_ORDER,
    JUDGE_APPROVED_THE_ORDER_CLOAK,
    JUDGE_DIRECTION_ORDER_CLOAK,
    JUDGE_DIRECTION_ORDER,
    REQUEST_FOR_INFORMATION,
    LIST_FOR_HEARING,
    CONCURRENT_WRITTEN_REP,
    SEQUENTIAL_WRITTEN_REP,
    APPLICATION_CHANGE_TO_WITH_NOTICE,
    NON_CRITERION
}
